# Generated by Django 4.2.5 on 2024-04-14 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0002_trash_created_at_trash_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trash',
            options={'ordering': ['-deletion_date'], 'verbose_name_plural': 'Recycle Bin'},
        ),
    ]
