# Generated by Django 4.2.5 on 2024-02-22 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_deleted', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=100)),
                ('contact_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contact.contactinformation')),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_deleted', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('partnership_date', models.DateField(auto_now_add=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contact.address')),
                ('contact_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contact.contactinformation')),
                ('logo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
