# Generated by Django 4.2.5 on 2024-04-09 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partnership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='featured',
            field=models.BooleanField(default=False, help_text='Mark this partner as featured', verbose_name='Featured'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='featured',
            field=models.BooleanField(default=False, help_text='Mark this team member as featured', verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contact_person',
            field=models.CharField(max_length=100, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partnership_date',
            field=models.DateField(auto_now_add=True, verbose_name='Partnership Date'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.CharField(max_length=100, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(max_length=100, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
