# Generated by Django 4.2.5 on 2024-04-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='My Dashboard', max_length=100)),
                ('primary_color', models.CharField(default='#007bff', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7)),
                ('email_from', models.EmailField(default='noreply@maishagirlssafehouse.org', max_length=254)),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=100)),
                ('email_port', models.IntegerField(default=587)),
                ('email_username', models.CharField(max_length=100)),
                ('email_password', models.CharField(max_length=100)),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('notification_email_recipients', models.CharField(blank=True, max_length=200, null=True)),
                ('use_original_images', models.BooleanField(default=True, help_text='If true, the original uploaded image will be displayed. If false, dynamic image versions will be used.')),
                ('image_quality', models.IntegerField(default=80, help_text='The quality of the dynamically generated image versions (0-100).')),
                ('image_max_size', models.IntegerField(default=1024, help_text='The maximum size (in pixels) of the dynamically generated image versions.')),
                ('enable_caching', models.BooleanField(default=True)),
                ('cache_timeout', models.IntegerField(default=3600, help_text='The number of seconds to cache responses.')),
                ('cache_backend', models.CharField(default='redis', help_text="The cache backend to use (e.g., 'redis', 'memcached', etc.).", max_length=50)),
                ('log_level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], default='INFO', max_length=20)),
                ('log_file_path', models.CharField(default='/var/log/dashboard.log', max_length=200)),
                ('log_file_size_limit', models.IntegerField(default=1048576, help_text='The maximum size (in bytes) of the log file before it is rotated.')),
                ('enable_two_factor_auth', models.BooleanField(default=False)),
                ('allowed_ip_ranges', models.CharField(blank=True, help_text="A comma-separated list of IP address ranges (e.g., '192.168.1.0/24,10.0.0.0/16')", max_length=200, null=True)),
                ('session_timeout', models.IntegerField(default=30, help_text='The number of minutes of inactivity before a user session expires.')),
                ('data_retention_period', models.IntegerField(default=30, help_text='The number of days to keep data before it is automatically purged.')),
                ('enable_data_archiving', models.BooleanField(default=True)),
                ('archive_storage_location', models.CharField(default='s3://my-dashboard-archive', max_length=200)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
