# Generated by Django 4.2.5 on 2024-04-08 17:10

from django.db import migrations, models
import django.db.models.deletion
import media.utils
import media.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deletion_scheduled', models.BooleanField(default=False)),
                ('deletion_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('file', models.FileField(blank=True, null=True, upload_to=media.validator.custom_upload_path)),
                ('object_id', media.utils.OrphanTrackingField(blank=True, null=True)),
                ('is_orphan', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('resize_mode', models.CharField(choices=[('NEAREST', 'Nearest'), ('BILINEAR', 'Bilinear'), ('BICUBIC', 'Bicubic'), ('LANCZOS', 'Lanczos')], default='BICUBIC', max_length=10)),
                ('versions', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deletion_scheduled', models.BooleanField(default=False)),
                ('deletion_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('file', models.FileField(blank=True, null=True, upload_to=media.validator.custom_upload_path)),
                ('object_id', media.utils.OrphanTrackingField(blank=True, null=True)),
                ('is_orphan', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deletion_scheduled', models.BooleanField(default=False)),
                ('deletion_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('file', models.FileField(blank=True, null=True, upload_to=media.validator.custom_upload_path)),
                ('object_id', media.utils.OrphanTrackingField(blank=True, null=True)),
                ('is_orphan', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Icons',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deletion_scheduled', models.BooleanField(default=False)),
                ('deletion_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('file', models.FileField(blank=True, null=True, upload_to=media.validator.custom_upload_path)),
                ('object_id', media.utils.OrphanTrackingField(blank=True, null=True)),
                ('is_orphan', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
