# Generated by Django 4.2.5 on 2024-04-14 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='media.image')),
                ('image2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.image')),
            ],
            options={
                'unique_together': {('image1', 'image2')},
            },
        ),
    ]
