# Generated by Django 4.2.5 on 2024-02-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='soft_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='soft_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='soft_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
