# Generated by Django 4.2.5 on 2024-02-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_document_soft_deleted_image_soft_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='large_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='image',
            name='medium_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='image',
            name='resize_mode',
            field=models.CharField(choices=[('NEAREST', 'Nearest'), ('BILINEAR', 'Bilinear'), ('BICUBIC', 'Bicubic'), ('LANCZOS', 'Lanczos')], default='BICUBIC', max_length=10),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
    ]
