# Generated by Django 4.2.5 on 2024-04-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_similarimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=100, verbose_name='Cluster Name')),
                ('images', models.ManyToManyField(related_name='duplicate_images', to='media.image')),
            ],
            options={
                'verbose_name_plural': 'Duplicate Images',
            },
        ),
        migrations.DeleteModel(
            name='SimilarImage',
        ),
    ]
