# Generated by Django 4.2.5 on 2024-02-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_image_large_url_image_medium_url_image_resize_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='large_url',
        ),
        migrations.RemoveField(
            model_name='image',
            name='medium_url',
        ),
        migrations.RemoveField(
            model_name='image',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='image',
            name='versions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
