# Generated by Django 4.2.5 on 2024-02-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_remove_image_large_url_remove_image_medium_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='versions',
            new_name='image_versions',
        ),
    ]
