# Generated by Django 4.2.5 on 2024-05-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_duplicateimagecluster_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DuplicateImageCluster',
            new_name='SimilarPhoto',
        ),
        migrations.AlterModelOptions(
            name='similarphoto',
            options={'verbose_name_plural': 'Similar Photos'},
        ),
    ]
