# Generated by Django 4.2.5 on 2024-02-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_alter_document_file_alter_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, choices=[], null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, choices=[], null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, choices=[], null=True),
        ),
    ]
