# Generated by Django 4.2.5 on 2024-05-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_rename_duplicateimagecluster_similarphoto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': 'Photos'},
        ),
        migrations.AddField(
            model_name='document',
            name='similarity_explored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='icon',
            name='similarity_explored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='similarity_explored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='similarity_explored',
            field=models.BooleanField(default=False),
        ),
    ]
